"""add_currency_to_program

Revision ID: 13add424a7c4
Revises: 1a89cc49ecec
Create Date: 2026-04-29 02:18:19.619707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13add424a7c4'
down_revision: Union[str, None] = '1a89cc49ecec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('currency', sa.String(length=10), nullable=False, server_default='MYR'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'currency')
    # ### end Alembic commands ###
