"""add_payment_system

Revision ID: 1a89cc49ecec
Revises: c3b98e82e506
Create Date: 2026-04-29 00:15:27.900794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a89cc49ecec'
down_revision: Union[str, None] = 'c3b98e82e506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type first
    payment_status_enum = sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus')
    payment_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('hitpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('payment_url', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['program_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_hitpay_payment_id'), 'payments', ['hitpay_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_registration_id'), 'payments', ['registration_id'], unique=False)
    op.add_column('program_registrations', sa.Column('amount_paid', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('program_registrations', sa.Column('balance_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('program_registrations', sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False, server_default='PENDING'))
    op.add_column('program_registrations', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('programs', sa.Column('price', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('programs', sa.Column('is_refundable', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('programs', sa.Column('refund_percentage', sa.Float(), nullable=False, server_default='100.0'))
    op.add_column('programs', sa.Column('allow_partial_payment', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('programs', sa.Column('minimum_deposit', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('programs', sa.Column('balance_due_days', sa.Integer(), nullable=False, server_default='7'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'balance_due_days')
    op.drop_column('programs', 'minimum_deposit')
    op.drop_column('programs', 'allow_partial_payment')
    op.drop_column('programs', 'refund_percentage')
    op.drop_column('programs', 'is_refundable')
    op.drop_column('programs', 'price')
    op.drop_column('program_registrations', 'due_date')
    op.drop_column('program_registrations', 'payment_status')
    op.drop_column('program_registrations', 'balance_amount')
    op.drop_column('program_registrations', 'amount_paid')
    op.drop_index(op.f('ix_payments_registration_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_hitpay_payment_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
