"""add_program_and_registration_tables

Revision ID: 27ca3e52f2c9
Revises: ebc011035a22
Create Date: 2026-04-28 14:07:59.403338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ca3e52f2c9'
down_revision: Union[str, None] = 'ebc011035a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('class_id', sa.String(length=50), nullable=False),
    sa.Column('date_range', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_city'), 'programs', ['city'], unique=False)
    op.create_index(op.f('ix_programs_class_id'), 'programs', ['class_id'], unique=False)
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_table('program_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('nric_last_4', sa.String(length=4), nullable=False),
    sa.Column('preferred_language', sa.String(length=50), nullable=False),
    sa.Column('meal_preference', sa.Enum('VEGETARIAN', 'NON_VEGETARIAN', name='mealpreference'), nullable=False),
    sa.Column('health_issues', sa.Text(), nullable=False),
    sa.Column('referred_by', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=False),
    sa.Column('emergency_contact_relation', sa.String(length=100), nullable=False),
    sa.Column('discovery_source', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='registrationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_registrations_id'), 'program_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_program_registrations_program_id'), 'program_registrations', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_registrations_user_id'), 'program_registrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_registrations_user_id'), table_name='program_registrations')
    op.drop_index(op.f('ix_program_registrations_program_id'), table_name='program_registrations')
    op.drop_index(op.f('ix_program_registrations_id'), table_name='program_registrations')
    op.drop_table('program_registrations')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_class_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_city'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
