"""create cms_pages table and update sections

Revision ID: 619ae68160fc
Revises: a7f4345ff40d
Create Date: 2026-04-30 00:38:28.973431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619ae68160fc'
down_revision: Union[str, None] = 'a7f4345ff40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_pages_name'), 'cms_pages', ['name'], unique=True)
    op.execute("UPDATE sections SET page_id = NULL WHERE page_id = ''")
    op.alter_column('sections', 'page_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='page_id::integer')
    op.drop_index('ix_sections_pagename', table_name='sections')
    op.create_foreign_key(None, 'sections', 'cms_pages', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sections', 'pagename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('pagename', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_index('ix_sections_pagename', 'sections', ['pagename'], unique=False)
    op.alter_column('sections', 'page_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_cms_pages_name'), table_name='cms_pages')
    op.drop_table('cms_pages')
    # ### end Alembic commands ###
