"""add_dynamic_options_to_program

Revision ID: 6a7e30ef7682
Revises: 8578ac07f1b2
Create Date: 2026-04-28 23:23:06.158847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7e30ef7682'
down_revision: Union[str, None] = '8578ac07f1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('languages', sa.JSON(), nullable=True))
    op.add_column('programs', sa.Column('discovery_sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'discovery_sources')
    op.drop_column('programs', 'languages')
    # ### end Alembic commands ###
