"""add_program_name_to_program

Revision ID: 8578ac07f1b2
Revises: 359d1bbde19c
Create Date: 2026-04-28 15:08:40.790465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8578ac07f1b2'
down_revision: Union[str, None] = '359d1bbde19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('program_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'program_name')
    # ### end Alembic commands ###
