"""add page_id and pagename to sections

Revision ID: a7f4345ff40d
Revises: f1acf529bd65
Create Date: 2026-04-29 23:17:29.805037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f4345ff40d'
down_revision: Union[str, None] = 'f1acf529bd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('page_id', sa.String(length=100), nullable=True))
    op.add_column('sections', sa.Column('pagename', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_sections_page_id'), 'sections', ['page_id'], unique=False)
    op.create_index(op.f('ix_sections_pagename'), 'sections', ['pagename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_pagename'), table_name='sections')
    op.drop_index(op.f('ix_sections_page_id'), table_name='sections')
    op.drop_column('sections', 'pagename')
    op.drop_column('sections', 'page_id')
    # ### end Alembic commands ###
