"""Add landing page models

Revision ID: c26ab35e44c4
Revises: 
Create Date: 2026-03-12 17:44:36.339479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26ab35e44c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('support_text', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('background_image_url', sa.String(length=255), nullable=False),
    sa.Column('form_background_image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enlightenment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('background_image_url', sa.String(length=255), nullable=False),
    sa.Column('founder_name', sa.String(length=255), nullable=False),
    sa.Column('founder_role', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date_text', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('button_text', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footer_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('newsletter_title', sa.String(length=255), nullable=False),
    sa.Column('newsletter_description', sa.Text(), nullable=False),
    sa.Column('facebook_url', sa.String(length=255), nullable=False),
    sa.Column('instagram_url', sa.String(length=255), nullable=False),
    sa.Column('twitter_url', sa.String(length=255), nullable=False),
    sa.Column('mail_url', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=False),
    sa.Column('copyright_text', sa.String(length=255), nullable=False),
    sa.Column('background_image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('button_text', sa.String(length=100), nullable=False),
    sa.Column('background_image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navbar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=False),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('button_text', sa.String(length=100), nullable=False),
    sa.Column('background_image_url', sa.String(length=255), nullable=False),
    sa.Column('card1_title', sa.String(length=255), nullable=False),
    sa.Column('card1_image_url', sa.String(length=255), nullable=False),
    sa.Column('card2_title', sa.String(length=255), nullable=False),
    sa.Column('card2_image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_role', sa.String(length=255), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_slug'), 'user', ['slug'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_slug'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('testimonial')
    op.drop_table('program_section')
    op.drop_table('navbar')
    op.drop_table('hero')
    op.drop_table('footer_info')
    op.drop_table('event')
    op.drop_table('enlightenment')
    op.drop_table('contact_info')
    # ### end Alembic commands ###
