"""add_introducer_fields_to_registration

Revision ID: c3b98e82e506
Revises: 6a7e30ef7682
Create Date: 2026-04-28 23:29:52.838798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b98e82e506'
down_revision: Union[str, None] = '6a7e30ef7682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_registrations', sa.Column('introducer_name', sa.String(length=255), nullable=True))
    op.add_column('program_registrations', sa.Column('introducer_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_registrations', 'introducer_phone')
    op.drop_column('program_registrations', 'introducer_name')
    # ### end Alembic commands ###
