"""Add membership and membership registration tables

Revision ID: d250e2bf5ecb
Revises: 263cbcccf71a
Create Date: 2026-05-04 14:20:09.799282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd250e2bf5ecb'
down_revision: Union[str, None] = '263cbcccf71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attended_programs_options', sa.JSON(), nullable=True),
    sa.Column('membership_types', sa.JSON(), nullable=True),
    sa.Column('custom_questions', sa.JSON(), nullable=True),
    sa.Column('interest_options', sa.JSON(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_table('membership_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('attended_programs', sa.JSON(), nullable=True),
    sa.Column('membership_type', sa.String(length=255), nullable=False),
    sa.Column('monthly_contribution', sa.Float(), nullable=False),
    sa.Column('custom_answers', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('agreed_to_terms', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_registrations_id'), 'membership_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_membership_registrations_membership_id'), 'membership_registrations', ['membership_id'], unique=False)
    op.create_index(op.f('ix_membership_registrations_user_id'), 'membership_registrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_registrations_user_id'), table_name='membership_registrations')
    op.drop_index(op.f('ix_membership_registrations_membership_id'), table_name='membership_registrations')
    op.drop_index(op.f('ix_membership_registrations_id'), table_name='membership_registrations')
    op.drop_table('membership_registrations')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.drop_table('memberships')
    # ### end Alembic commands ###
