"""add brand_name to navbar

Revision ID: d471331b2f3d
Revises: b8222de48b7d
Create Date: 2026-03-13 10:42:41.851301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd471331b2f3d'
down_revision: Union[str, None] = 'b8222de48b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_section')
    op.drop_table('testimonial_section')
    op.add_column('navbar', sa.Column('brand_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('navbar', 'brand_name')
    op.create_table('testimonial_section',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('background_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('testimonial_section_pkey'))
    )
    op.create_table('events_section',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('background_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('events_section_pkey'))
    )
    # ### end Alembic commands ###
