"""add_detailed_profile_fields

Revision ID: ebc011035a22
Revises: bd2d758861e7
Create Date: 2026-04-28 13:14:58.187412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc011035a22'
down_revision: Union[str, None] = 'bd2d758861e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender')
    gender_enum.create(op.get_bind())
    
    op.alter_column('users', 'name', new_column_name='full_name')
    op.add_column('users', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.drop_column('users', 'address')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
