"""add_payment_metadata_to_registration

Revision ID: f1acf529bd65
Revises: 13add424a7c4
Create Date: 2026-04-29 02:38:27.786058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1acf529bd65'
down_revision: Union[str, None] = '13add424a7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_registrations', sa.Column('payment_request_id', sa.String(length=255), nullable=True))
    op.add_column('program_registrations', sa.Column('hitpay_payment_id', sa.String(length=255), nullable=True))
    op.add_column('program_registrations', sa.Column('payment_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_registrations', 'payment_url')
    op.drop_column('program_registrations', 'hitpay_payment_id')
    op.drop_column('program_registrations', 'payment_request_id')
    # ### end Alembic commands ###
